//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSconsumir.WSdeber {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSdeber.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listacargoxempelado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listacargoxempelado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listacargoxempelado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListacargoxempeladoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listacargon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listacargon(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listacargon", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListacargonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WsInsertarcargo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WsInsertarcargo(string descripcion, int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WsInsertarcargo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WsInsertarcargoAsync(string descripcion, int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Wseditarcargo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Wseditarcargo(int id, string descripcion, int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Wseditarcargo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WseditarcargoAsync(int id, string descripcion, int empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarcargo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet eliminarcargo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarcargo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> eliminarcargoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listarempleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listarempleado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listarempleado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarempleadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listarempresas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listarempresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listarempresas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarempresasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listardepartamentosxempresa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listardepartamentosxempresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listardepartamentosxempresa", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListardepartamentosxempresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadepaN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadepaN(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadepaN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadepaNAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertardep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Insertardep(string descripcion, int empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertardep", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertardepAsync(string descripcion, int empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editardep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet editardep(int id, string descripcion, int empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editardep", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> editardepAsync(int id, string descripcion, int empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminardep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet eliminardep(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminardep", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> eliminardepAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WSconsumir.WSdeber.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WSconsumir.WSdeber.WebServiceSoap>, WSconsumir.WSdeber.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listacargoxempelado() {
            return base.Channel.Listacargoxempelado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListacargoxempeladoAsync() {
            return base.Channel.ListacargoxempeladoAsync();
        }
        
        public System.Data.DataSet Listacargon(int id) {
            return base.Channel.Listacargon(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListacargonAsync(int id) {
            return base.Channel.ListacargonAsync(id);
        }
        
        public System.Data.DataSet WsInsertarcargo(string descripcion, int empleado) {
            return base.Channel.WsInsertarcargo(descripcion, empleado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WsInsertarcargoAsync(string descripcion, int empleado) {
            return base.Channel.WsInsertarcargoAsync(descripcion, empleado);
        }
        
        public System.Data.DataSet Wseditarcargo(int id, string descripcion, int empleado) {
            return base.Channel.Wseditarcargo(id, descripcion, empleado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WseditarcargoAsync(int id, string descripcion, int empleado) {
            return base.Channel.WseditarcargoAsync(id, descripcion, empleado);
        }
        
        public System.Data.DataSet eliminarcargo(int id) {
            return base.Channel.eliminarcargo(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> eliminarcargoAsync(int id) {
            return base.Channel.eliminarcargoAsync(id);
        }
        
        public System.Data.DataSet Listarempleado() {
            return base.Channel.Listarempleado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarempleadoAsync() {
            return base.Channel.ListarempleadoAsync();
        }
        
        public System.Data.DataSet Listarempresas() {
            return base.Channel.Listarempresas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarempresasAsync() {
            return base.Channel.ListarempresasAsync();
        }
        
        public System.Data.DataSet Listardepartamentosxempresa() {
            return base.Channel.Listardepartamentosxempresa();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListardepartamentosxempresaAsync() {
            return base.Channel.ListardepartamentosxempresaAsync();
        }
        
        public System.Data.DataSet ListadepaN(int id) {
            return base.Channel.ListadepaN(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadepaNAsync(int id) {
            return base.Channel.ListadepaNAsync(id);
        }
        
        public System.Data.DataSet Insertardep(string descripcion, int empresa) {
            return base.Channel.Insertardep(descripcion, empresa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertardepAsync(string descripcion, int empresa) {
            return base.Channel.InsertardepAsync(descripcion, empresa);
        }
        
        public System.Data.DataSet editardep(int id, string descripcion, int empresa) {
            return base.Channel.editardep(id, descripcion, empresa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> editardepAsync(int id, string descripcion, int empresa) {
            return base.Channel.editardepAsync(id, descripcion, empresa);
        }
        
        public System.Data.DataSet eliminardep(int id) {
            return base.Channel.eliminardep(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> eliminardepAsync(int id) {
            return base.Channel.eliminardepAsync(id);
        }
    }
}
